[package]
name = "cobia_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = {version="1.0", features = ["full","parsing","printing"]}
quote = "1.0"
proc-macro2 = "1.0"


